### ISSUE TITLE
The page source link is broken

### ISSUE THREAD

**Issue by awulkan** [TalonCommunity/Wiki#113]
When clicking the 'source' link on a page I end up in an infinite redirect loop.

![image](https://i.imgur.com/tnK8q0F.png)

The link goes to `https://talon.wiki/blob/gh-pages//getting_started.md`
Which then redirects to: `https://talon.wiki/new/gh-pages?filename=wiki/gh-pages.md`, where it gets stuck.

**Comment by awulkan** [comment]
Edit, in fact, all links in that navbar are broken.

**Comment by 2shea** [comment]
Ah, I must have broken these  over the  weekend when I migrated to netlify. Thanks for pointing this out.
