### ISSUE TITLE
Body text is not black any more

### ISSUE THREAD

**Issue by rntz** [TalonCommunity/Wiki#123]
The color of the text on the wiki seems to have become gray again, which makes it significantly harder to read for me. I thought I fixed this in #11.

**Comment by 2shea** [comment]
You did fix it, and I broke it :/ I have a PR that should fix it - just waiting for the build to be a success https://github.com/TalonCommunity/Wiki/pull/122

**Comment by 2shea** [comment]
I broke the loading of the custom css.

**Comment by 2shea** [comment]
I think this should be fixed now. If you have any further issues, feel free to reopen or mention it in #talon-docs.
