### ISSUE TITLE
Unable to make changes in place

### ISSUE THREAD

**Issue by AndrewDant** [TalonCommunity/Wiki#165]
Whenever I try to make and save changes to the wiki using the in place editor it fails and I get the below error message which doesn't help me to debug what's wrong.

![image](https://user-images.githubusercontent.com/30133577/159176847-97681e86-acbd-4eda-bc31-e9600fd43bb0.png)

**Comment by AndrewDant** [comment]
Here is the response from that request in the networking tab of dev tools:

{
  "message": "You must be logged in to do that.",
  "documentation_url": "https://docs.github.com/rest/guides/getting-started-with-the-rest-api#authentication"
}

This made it clear to me that I needed to figure out how to login to github in the current context. I figured out I could do that by clicking on the green square in the bottom right corner and giving Prose permission for my github account. This was very easy once I figured out that's what was needed but there was nothing leading me to do that prior to making changes.

**Comment by splondike** [comment]
I guess we can do one of these things:

* Fix this long standing Prose.io issue: https://github.com/prose/prose/issues/643
* Just remove the Prose.io links and rely on the github ones that are already in the nav. This would lose shortcut buttons to add headers etc.
* Find and set up an alternative to Prose.io.

I guess we don't know how many people have been turned away from their edits by this, but I think I'd vote for option #2 (just remove the Prose.io links+integration).

**Comment by 2shea** [comment]
I'm in favor of removing the Prose links. They aren't used that often, and IMO not worth maintaining since we have alternatives like the GitHub UI and folks have to be signed into GitHub to use Prose anyway.

**Comment by C-Loftus** [comment]
Closing since stale. Refactor will allow us to edit any page relatively easily, so long as the user has a github account. (i.e. see the `edit` button at the bottom of any docusaurus article). Not the absolute lowest friction option, but doesn't require any local cloning
https://docusaurus.io/docs
