### ISSUE TITLE
Setting up dev environment in Windows requires webrick

### ISSUE THREAD

**Issue by Spiteless** [TalonCommunity/Wiki#188]
Hey there,

I'm not really familiar with Ruby or Jekyll, I was trying to test some features localy and got the site to build, but needed to both add webrick, and change the port number on my run command to due to port 4000 either being occupied or having a permissions issue.

[Issue referencing needing to add webrick](https://github.com/jekyll/jekyll/issues/8523)

----
Port issue error and some resources below I looked at:

    `bind': Permission denied - bind(2) for 127.0.0.1:4000 (Errno::EACCES)

* [One](https://superuser.com/questions/1437780/how-to-fix-listen-eacces-permission-denied-on-any-port)
* [Two](https://github.com/rails/rails/issues/33346)
* [Three](https://stackoverflow.com/questions/43739386/rails-permission-denied-bind2-for-127-0-0-1-port-3000-errnoeacces)

Ultimately adding a port number to the serve command got around this problem.

    bundle exec jekyll serve --port 4001

Complete error code:

    jekyll 3.9.2 | Error:  Permission denied - bind(2) for 127.0.0.1:4000
    C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:201:in `bind': Permission denied - bind(2) for 127.0.0.1:4000 (Errno::EACCES)
        from C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:201:in `listen'
        from C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:765:in `block in tcp_server_sockets'
        from C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:227:in `each'
        from C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:227:in `foreach'
        from C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:763:in `tcp_server_sockets'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/utils.rb:60:in `create_listeners'    
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/server.rb:130:in `listen'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/server.rb:111:in `initialize'        
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:47:in `initialize'     
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:229:in `new'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:229:in `start_up_webrick'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:104:in `process'     
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'        
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'      
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby31-x64/bin/jekyll:25:in `load'
        from C:/Ruby31-x64/bin/jekyll:25:in `<main>'

Branch at: [Spiteless/windows_dev_setup](https://github.com/Spiteless/Wiki/tree/windows_dev_setup)

**Comment by C-Loftus** [comment]
Closing since stale. New wiki refactor will allow `npm` and be easier to test locally.
