### ISSUE TITLE
Basic customization - Keyboard shortcuts; Needs updating

### ISSUE THREAD

**Issue by PastTenseOfDraw** [TalonCommunity/Wiki#193]
I am told that adding Keyboard shorts cuts are now available for Windows but the wiki still says it is only an option for Mac.

https://github.com/TalonCommunity/Wiki/blob/main/basic_customization.md#keyboard-shortcuts

If there is a better way to submit a new issue, please let me know.

**Comment by splondike** [comment]
Thanks for the note, I've updated the docs.

This is a good way to submit an issue if you don't feel confident doing the updates yourself :+1: .
