### ISSUE TITLE
Suggestion: Make home page an introduction to Talon

### ISSUE THREAD

**Issue by jenmei** [TalonCommunity/Wiki#23]
When I first saw the wiki, I was a little confused where to start. I found it a little bit disorienting at the homepage is about contributing to the wiki instead of about the subject of the wiki. It would be great if the home page described talon and may talked about how best to use the wiki to get started with a link to the contribution page.

**Comment by emmakat** [comment]
@2shea thoughts?

**Comment by 2shea** [comment]
Oh yes, I agree the home page isn't the ideal content at the moment. I'm not sure yet what is best, but I was thinking it would be a landing page with some basic info and maybe links to other docs organized into sections or something, so it would be more obvious where to start, and help folks find what they need faster.

**Comment by 2shea** [comment]
I initially made it a "Contributing" doc to get people started in making contributions and because it was the first page I built, but yeah, it should change.

**Comment by 2shea** [comment]
I think this should be better now that I rearranged the content, but feel free to reopen if you had something else in mind.
