### ISSUE TITLE
Make examples clear whether they are for public or beta

### ISSUE THREAD

**Issue by 2shea** [TalonCommunity/Wiki#27]
Examples are included but they don't always say they are for beta or public. Would be good to make sure it's clearly marked.

**Comment by rntz** [comment]
Closing this because the beta has now been released publicly, and we have an issue (#52) for rewriting the wiki accordingly.

**Comment by gimpf** [comment]
Eeeeh... no. NewAPI is public, stuff like sconv model support is still beta-only.

**Comment by rntz** [comment]
yes, I know; read #52.

**Comment by gimpf** [comment]
yeah, just saw your updates in the commits, looks fine
