### ISSUE TITLE
The Slack Link from talonvoice.com is not working.  Is there another way I can join?

### ISSUE THREAD

**Issue by MaylinGood** [TalonCommunity/Wiki#271]
![Inactive Link](https://github.com/TalonCommunity/Wiki/assets/46846244/8525ff59-b690-4ec9-8e01-03b76d68c6f9)

**Comment by splondike** [comment]
I've let the owner of the site know about the issue, hopefully he'll put in a new link over the next day or so.

**Comment by splondike** [comment]
Link's been fixed, closing.
