### ISSUE TITLE
auto line-wrap text

### ISSUE THREAD

**Issue by 2shea** [TalonCommunity/Wiki#28]
Some text blobs are currently all on one line, which will be hard to read on wide monitors and will make future diffs hard to read. We should explore some automatic line wrapping.

**Comment by gimpf** [comment]
The github version is more like a preview -- it also doesn't process any jekyll magic.  Also, [Github Flavored Markdown](https://github.github.com/gfm/#soft-line-breaks) interprets newlines as softbreak.

**Comment by bhipple** [comment]
One nice thing about using standard-off-the-shelf markdown, aside from being familiar, is that automated formatting tools like [prettier](https://prettier.io/) can just format it all for you at the press of a button without everyone having to figure out what bespoke conventions are in place in this repo.  I'd be in favor of just running it with the default settings on this repo to ease contributions.  It's particularly nice for drive-by rare contributors who aren't as intimately familiar with the formatting style of the repo to have something "standard".

**Comment by C-Loftus** [comment]
Stale issue that will be fixed in refactor
