### ISSUE TITLE
Add how to access troubleshooting log instructions

### ISSUE THREAD

**Issue by tararoys** [TalonCommunity/Wiki#40]
In talon.wiki.troubleshooting In the section" talon does nothing when I speak," it talks about using the log to check if you’ve got your microphone on.

  I think instructions on how to access the log would be an effective addition to the troubleshooting section.  I would love a set of instructions on how to access the log on each operating system. That seems like information that would help people troubleshoot their own problems.

**Comment by tararoys** [comment]
In https://talon.wiki/unofficial_talon_docs/#speechdebug The speech.debug Information would be very useful duplicated into the troubleshooting https://talon.wiki/troubleshooting/ section, Since this prints out a debugging log to the console.

**Comment by C-Loftus** [comment]
Closing as stale
