### ISSUE TITLE
Unofficial talon docs page has a zooming issues on iPhone

### ISSUE THREAD

**Issue by tararoys** [TalonCommunity/Wiki#43]
https://talon.wiki/unofficial_talon_docs/  On this page, when I am using my iPhone, Soon as I take my finger off the screen the page zooms in in a very annoying way.  This is what I see on that page. The left hand section of text is cut off, and I am not permitted to zoom it back out so that I can see it. I don’t have this problem on any other page of the wiki so far.

**Comment by 2shea** [comment]
I think I remember seeing this issue you are talking about, and I think it's something related to wide table on the page.

**Comment by C-Loftus** [comment]
Closed since stale and will be resolved in refactor
