### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by sersorrel** [TalonCommunity/Wiki#50]
The API docs on the official Talon website are (by their own admission) incomplete at best, but the only other attempt at a set of organised API docs I could find was https://github.com/dwighthouse/unofficial-talonvoice-docs, which is over a year old and not up-to-date with the new public (previously "beta") release.

Would this be the right place for a set of community-maintained API docs for Talon?

**Comment by rntz** [comment]
Yes, this is the place for unofficial docs. We already have some efforts in that direction, see https://talon.wiki/unofficial_talon_docs/.
