### ISSUE TITLE
edit wiki in light of public release of new talon

### ISSUE THREAD

**Issue by rntz** [TalonCommunity/Wiki#52]
Most pages on the wiki were written before the new Talon version was publicly released, so a lot of them need rewriting. They tend to assume that readers have access to the beta channel, and refer to the legacy release for mac as the public release. We should instead call the old public version of talon "legacy", the current public version "public", and label things that only work in the beta as "beta". We should aim for most of the information on the wiki to be useful and accessible to public Talon users, and mark beta-specific information clearly.

- [x] Rewrite getting_started.md.
- [x] Rewrite advanced_talon.md.
- [ ] Check that the install process on getting_started.md is still accurate for public.
- [x] Fix the wav2letter set up instructions in getting_started.md; they currently link to #beta.
- [x] Fix up the FAQ.
- [x] Check that there are no other spurious references to the beta where they don't belong.

**Comment by 2shea** [comment]
I think this should get us almost there: https://github.com/TalonCommunity/Wiki/commit/58921912724ee4050414f00a0f78ff377df3fea4

I tried to remove all spurious references to beta. We should give the install processes some more attention to make sure they are accurate.
