### ISSUE TITLE
Remove commands from knausj other than the basics

### ISSUE THREAD

**Issue by 2shea** [TalonCommunity/Wiki#68]
We have examples of commands from the knausj repository, but maybe it's best to leave documentation of those commands to that repository. Maybe we leave just the basics: help, command history, wake up / sleep, dictation / command mode.

**Comment by C-Loftus** [comment]
Closing as stale. I think we have some the basics within `basic usage` at an acceptable level of detail. Doesn't seem like that repo is going to do much documentation beyond what it currently has. Think the next step is mainly to add other docs sections or use talon doc somehow
