### ISSUE TITLE
Information on configurations other than the knausj ought to be included and stashed somewhere

### ISSUE THREAD

**Issue by tararoys** [TalonCommunity/Wiki#86]
While deleting the advanced Talon page Emily and Tara decided that having links somewhere on the wiki to alternative configurations would be valuable to put somewhere under a more meaningful name than 'Advanced Talon'

## Alternative User Configurations

If you do not have anything specific in mind, start out using [knausj_talon](https://github.com/knausj85/knausj_talon), which has become the most shared Talon configuration.  Of course there are alternatives, but **only use one repository - they should not be mixed.**

| Talon Release | GitHub Repository | Description |
|-|-|
| **Public** | **[knausj85's knausj_talon](https://github.com/knausj85/knausj_talon)** | **The currently recommended go-to repository for general use** |
| Public | [Fidgetingbit's Talon Config](https://github.com/fidgetingbits/knausj_talon) | Fork of Knausj's config with VimSpeak support |
| Public | [mrob95's Talon Config](https://github.com/mrob95/MR-talon) | Mark Robert's Talon config with support for Windows dev tools (Windows Terminal, Mintty, Windows Workspaces) |

**Comment by C-Loftus** [comment]
Closing as stale
