### ISSUE TITLE
Section to explain how python interacts with talon files

### ISSUE THREAD

**Issue by 2shea** [TalonCommunity/Wiki#98]
We could do a better job at explaining how python and talon files interact. We could also include a minimum amount of code example, like this one that was posted in talon slack:

```
from talon import Module
mod = Module()
@mod.action_class
class Actions:
    def action1():
        """prints hi"""
        print('hi')
    def action2(name: str, number: int):
        """prints a name and number"""
        print(name, number)
```
this defines new functions in talonscript that can be used in a .talon file with the syntax user.action1() or user.action2("name", 5) 

```
hello world: user.action1()
block command:
    insert("hello world")
    key(ctrl-c)
    user.action2("name", 5)
```

**Comment by C-Loftus** [comment]
Added into example section in wiki
